cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: almacenamientoarchivos


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 10MB